### ISSUE TITLE
Arm Image

### ISSUE THREAD

**Issue by ryoppippi** [qmk/qmk_base_container#16]
### Description

I built qmk_base_container on apple silicon mac.

https://hub.docker.com/layers/ryoppippi/qmk_base_container/latest/images/sha256-9938c05d27bca659390df460ee59e44fa70ef045174335d74db2911119626e24?context=repo

I hope you guys officially support the arm container on docker hub.
Or if you guys are ok, please upload my image to your dockerhub repository.

**Comment by skullydazed** [comment]
We'd love to support arm images. Would you be open to helping us do that?

Since dockerhub discontinued their free build service we have been switching to github actions for all our builds. I've just submitted PR #17 to switch base_container over, but that still builds for amd64. If you can work out a github action to build an AS image as well we'd love to include it.

**Comment by ryoppippi** [comment]
@skullydazed thank you for your reply.
I will create PR to support arm and amd64 arch!
